log_format google_manager_http_test '$remote_addr $time_local "$request_method $uri" $status $body_bytes_sent';

server {
    listen 80;
    server_name 123.206.210.86;
    access_log /var/log/nginx/google-manager-http-test-access.log google_manager_http_test;
    client_max_body_size 2M;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 3s;
    proxy_read_timeout 120s;
    proxy_buffering off;

    location ^~ /health/ {
        allow 127.0.0.1;
        deny all;
        proxy_pass http://127.0.0.1:8002;
    }

    location / {
        proxy_pass http://127.0.0.1:8002;
        proxy_cookie_flags session nosecure;
    }
}
